// Auto-discovers optimized image variants generated by scripts/optimize-images.mjs
// Each base name (e.g. "hero-ssg-vehicle") has:
//   - webp variants at multiple widths (400/800/1600 etc.)
//   - a single jpg fallback at the largest width
const webps = import.meta.glob("./*-*.webp", { eager: true, query: "?url", import: "default" }) as Record<string, string>;
const jpgs = import.meta.glob("./*-*.jpg", { eager: true, query: "?url", import: "default" }) as Record<string, string>;

export type ImgVariant = { url: string; w: number };
export type ImgAsset = {
  webp: ImgVariant[];   // sorted ascending by width
  fallback: ImgVariant; // largest jpg
  largest: number;      // largest known width
};

const map = new Map<string, { webp: ImgVariant[]; fallback?: ImgVariant }>();

function ensure(name: string) {
  let entry = map.get(name);
  if (!entry) {
    entry = { webp: [] };
    map.set(name, entry);
  }
  return entry;
}

const RE = /\.\/(.+)-(\d+)\.(webp|jpg)$/;
for (const [path, url] of Object.entries({ ...webps, ...jpgs })) {
  const m = path.match(RE);
  if (!m) continue;
  const [, name, wStr, ext] = m;
  const w = parseInt(wStr, 10);
  const entry = ensure(name);
  if (ext === "webp") entry.webp.push({ url, w });
  else if (!entry.fallback || w > entry.fallback.w) entry.fallback = { url, w };
}

const assets = new Map<string, ImgAsset>();
for (const [name, entry] of map) {
  if (!entry.fallback) continue;
  entry.webp.sort((a, b) => a.w - b.w);
  const largest = Math.max(entry.fallback.w, ...entry.webp.map((v) => v.w));
  assets.set(name, { webp: entry.webp, fallback: entry.fallback, largest });
}

export function getImage(name: string): ImgAsset {
  const a = assets.get(name);
  if (!a) throw new Error(`No optimized image found for "${name}". Available: ${[...assets.keys()].join(", ")}`);
  return a;
}

export function imageSrcSet(a: ImgAsset): string {
  return a.webp.map((v) => `${v.url} ${v.w}w`).join(", ");
}
